Code_Challenge/Code_Challenge/force-app/main/default/objects/Customer__c/Customer__c.object-meta.xml
<CustomObject>
    <description>Contain the customers existing in the Electric Company</description>
    <label>Customer</label>
    <nameField>
        <displayFormat>C-{00000000}</displayFormat>
        <label>Customer Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Customers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

CODING_CHALLENGE/MeterReader/force-app/main/default/objects/Customer__c/fields/Customer_Email__c.field-meta.xml
<CustomField>
    <fullName>Customer_Email__c</fullName>
    <description>Contains the email to contact the customer</description>
    <inlineHelpText>Contains the email to contact the customer</inlineHelpText>
    <label>Customer Email</label>
    <type>Email</type>
</CustomField>

CODING_CHALLENGE/MeterReader/force-app/main/default/objects/Customer__c/fields/External_ID__c.field-meta.xml
<CustomField>
    <fullName>External_ID__c</fullName>
    <description>Contains the external ID related to the customer, this external ID helps to find the user in Salesforce</description>
    <externalId>true</externalId>
    <inlineHelpText>Contains the external ID related to the customer, this external ID helps to find the user in Salesforce</inlineHelpText>
    <label>External ID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

CODING_CHALLENGE/MeterReader/force-app/main/default/objects/Customer__c/fields/Phone__c.field-meta.xml
<CustomField>
    <fullName>Phone__c</fullName>
    <description>Contains the telephone number for the client</description>
    <inlineHelpText>Contains the telephone number for the client</inlineHelpText>
    <label>Phone</label>
    <type>Phone</type>
</CustomField>

CODING_CHALLENGE/MeterReader/force-app/main/default/objects/Meter__c/Meter__c.object-meta.xml
<CustomObject>
    <description>Contains the meters available in the system to collect data</description>
    <label>Meter</label>
    <nameField>
        <displayFormat>M-{000000}</displayFormat>
        <label>Meter Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Meters</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Code_Challenge/force-app/main/default/objects/Meter__c/fields/Customer__c.field-meta.xml
<CustomField>
    <fullName>Customer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Holds the customer related to the meter</description>
    <label>Customer</label>
    <referenceTo>Customer__c</referenceTo>
    <relationshipLabel>Meters</relationshipLabel>
    <relationshipName>Meters</relationshipName>
    <type>Lookup</type>
</CustomField>

CODING_CHALLENGE/MeterReader/force-app/main/default/objects/Meter__c/fields/External_ID__c.field-meta.xml
<CustomField>
    <fullName>External_ID__c</fullName>
    <description>Contains the external id for the meter, this external ID could be the id used in the company which created the meter and we use it to relate this id to the salesforce id</description>
    <externalId>true</externalId>
    <inlineHelpText>Contains the external id for the meter, this external ID could be the id used in the company which created the meter and we use it to relate this id to the salesforce id</inlineHelpText>
    <label>External ID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Code_Challenge/Code_Challenge/force-app/main/default/objects/Meter__c/fields/Supplier__c.field-meta.xml
<CustomField>
    <fullName>Supplier__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Contains which supplier is resposable for the meter reader</description>
    <inlineHelpText>Contains which supplier is resposable for the meter reader</inlineHelpText>
    <label>Supplier</label>
    <referenceTo>Supplier__c</referenceTo>
    <relationshipLabel>Meters</relationshipLabel>
    <relationshipName>Meters</relationshipName>
    <type>Lookup</type>
</CustomField>

Code_Challenge/Code_Challenge/force-app/main/default/objects/Supplier__c/Supplier__c.object-meta.xml
<CustomObject>
    <description>Holds the suppliers available in the system</description>
    <label>Supplier</label>
    <nameField>
        <displayFormat>S-{000000}</displayFormat>
        <label>Supplier Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Suppliers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Code_Challenge/Code_Challenge/force-app/main/default/objects/Supplier__c/fields/Code__c.field-meta.xml
<CustomField>
    <fullName>Code__c</fullName>
    <description>Holds the code for the supplier</description>
    <label>Code</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Code_Challenge/force-app/main/default/objects/Supplier__c/fields/External_ID__c.field-meta.xml
<CustomField>
    <fullName>External_ID__c</fullName>
    <description>Contains the external ID from the supplier which provides the service to the user</description>
    <externalId>true</externalId>
    <inlineHelpText>Contains the external ID from the supplier which provides the service to the user</inlineHelpText>
    <label>External ID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

CODING_CHALLENGE/MeterReader/force-app/main/default/classes/HelperMeterReaderTest.cls
@isTest(seeAllData=false)
public class HelperMeterReaderTest {
    
        
    //This method will test the get data process using a ApexMockCallout, this method also test the url is valid.
    @isTest
    static void testGetData() 
    {
        Test.setMock(HttpCalloutMock.class, new MeterReaderHttpCalloutMock());
        System.AssertEquals('POSTED',HelperMeterReader.getMeterReader('https://testscenario/meter-read',false,null));
    }
    //Test when the url is null
    @isTest
    static void testGetDataNullURL() 
    {
        Test.setMock(HttpCalloutMock.class, new MeterReaderHttpCalloutMock());
        System.AssertEquals('UNEXPECTED_ERROR',HelperMeterReader.getMeterReader(null,false,null));
    }
    //This method will test the get data process using a ApexMockCallout, this method also test the url is valid and test for more than one meter reading.
    @isTest
    static void testGetDataMultiMeterReading() 
    {
        jsonTest = jsonTestMultiRecord;
        Test.setMock(HttpCalloutMock.class, new MeterReaderHttpCalloutMock());
        System.AssertEquals('POSTED',HelperMeterReader.getMeterReader('https://testscenario/meter-read',false,null));
    }
    //This method will test the get data process using a ApexMockCallout and passing json per parameters.
    @isTest
    static void testGetDataWithDummyData() 
    {
        
        Test.setMock(HttpCalloutMock.class, new MeterReaderHttpCalloutMock());
        System.AssertEquals('POSTED',HelperMeterReader.getMeterReader('https://testscenario/meter-read',false,jsonTest));
    }
    //This method will test the get data process using a ApexMockCallout, this method also test the url is not valid.
    @isTest
    static void testGetDataInvalidUrl() 
    {
        Test.setMock(HttpCalloutMock.class, new MeterReaderHttpCalloutMock());
        System.AssertEquals('INVALID_URL',HelperMeterReader.getMeterReader('https://testscenario/read',false,null));
    }
    //This method will test what happens when there is not data in the JSON received.
    @isTest
    static void testGetDataEmptyJSON() 
    {
        jsonTest = '';
        Test.setMock(HttpCalloutMock.class, new MeterReaderHttpCalloutMock());
        System.AssertEquals('MALFORMAT_JSON',HelperMeterReader.getMeterReader('https://testscenario/meter-read',false,null));
    }
    //This method will test what happens when the JSON is not formatted correctly.
    @isTest
    static void testGetDataWrongJSON() 
    {
        jsonTest = jsonTestMalFormated;
        Test.setMock(HttpCalloutMock.class, new MeterReaderHttpCalloutMock());
        System.AssertEquals('MALFORMAT_JSON',HelperMeterReader.getMeterReader('https://testscenario/meter-read',false,null));
    }
    //This method will test what happens when connection fails.
    @isTest
    static void testGetWhenErrorInConnection() 
    {
        Test.setMock(HttpCalloutMock.class, new MeterReaderHttpCalloutMock());
        System.AssertEquals('MALFORMAT_JSON',HelperMeterReader.getMeterReader('https://testscenario/meter-read/300',false,null));
    }
    //This method will test to save data existing records in the org.
    @isTest
    static void testSaveDataWithDataInOrg() 
    {
        createData();
        List<MeterReader> lstMeters = HelperMeterReader.validateJSONAndGenerateRecords(jsonTest);
        System.AssertEquals('OK',HelperMeterReader.storeRecords(lstMeters));
    }
    //This method will test the present data process.
    @isTest
    static void testPostData()
    {
        List<MeterReader> lstMeters = HelperMeterReader.validateJSONAndGenerateRecords(jsonTest);
        Test.setMock(HttpCalloutMock.class, new MeterReaderHttpCalloutMock());
        System.AssertEquals('POSTED',HelperMeterReader.generatePresent(lstMeters,'https://testscenario/meter-read',false));
    }
    //This method will test the insertion of the data in present method.
    @isTest
    static void testPostDataInsertData()
    {
        Test.startTest();
            List<MeterReader> lstMeters = HelperMeterReader.validateJSONAndGenerateRecords(jsonTest);
            HelperMeterReader.storeRecords(lstMeters);
            for(MeterReader meters : lstMeters)
            {
                meters.customerId = [SELECT Id FROM Customer__c limit 1].Id;
                meters.serialNumber = [SELECT Id FROM Meter__c limit 1].Id;
                meters.mpxn = [SELECT Id FROM Supplier__c limit 1].Id;
            }
        Test.stopTest();

        Test.setMock(HttpCalloutMock.class, new MeterReaderHttpCalloutMock());
        System.AssertEquals('POSTED',HelperMeterReader.generatePresent(lstMeters,'https://testscenario/meter-read',true));
    }

    //This method will test how the routine works when POSTING JSON when it is malformated.
    @isTest
    static void testPostDataWithWrongJSON()
    {
     
        List<MeterReader> lstMeters = HelperMeterReader.validateJSONAndGenerateRecords(jsonTestMalFormated);
        Test.setMock(HttpCalloutMock.class, new MeterReaderHttpCalloutMock());
        System.AssertEquals('FAILED_PRESENT',HelperMeterReader.generatePresent(lstMeters,'https://testscenario/meter-read',false));
    }
    //This method will test how the routine works when JSON is malformated.
    @isTest
    static void testPostDataWitConnectionError()
    {
     
        List<MeterReader> lstMeters = HelperMeterReader.validateJSONAndGenerateRecords(jsonTestMalFormated);
        Test.setMock(HttpCalloutMock.class, new MeterReaderHttpCalloutMock());
        System.AssertEquals('FAILED_PRESENT',HelperMeterReader.generatePresent(lstMeters,'https://testscenario/meter-read/300',false));
    }
    //Method to test the controller when pull the data to send to the lightning web component.
    @isTest
    static void testMeterReaderController()
    {
        MeterReaderController.getRecords();
    }
    /* GENERATE DATA FOR TEST SECTION */
    //Method to create dummy data to run the process.
    public static void createData()
    {
        List<Customer__c> listCustomers = new List<Customer__c>();
        List<Meter__c> listMeters = new List<Meter__c>();
        Supplier__c supplier = new Supplier__c(Code__c = 'BG',External_ID__c = '14582749');

        Database.insert(supplier);

        listCustomers.add(new Customer__c(Customer_Email__c = 'tester1@test.es', Phone__c = '0754896325', External_ID__c = 'identifier123'));
        listCustomers.add(new Customer__c(Customer_Email__c = 'tester2@test.es', Phone__c = '0751489632'));

        Database.insert(listCustomers);

        listMeters.add(new Meter__c(Customer__c = listCustomers.get(0).Id, Supplier__c = supplier.Id, External_ID__c = '27263927192'));
        listMeters.add(new Meter__c(Customer__c = listCustomers.get(1).Id, Supplier__c = supplier.Id));

        Database.insert(listMeters);
    }
    //JSON to test the process.
    public static String jsonTest = '{ ' +
                                    '"customerId": "identifier123",' + 
                                    '"serialNumber": "27263927192",' + 
                                    '"mpxn": "14582749",' +
                                    '"read": [' +
                                        '{"type": "ANYTIME", "registerId": "387373", "value": "2729"},' +
                                        '{"type": "NIGHT", "registerId": "387373", "value": "2892"}' +
                                    '],' + 
                                    '"readDate": "2017-11-20T16:19:48+00:00Z"' + 
                                    '}';
    //Malformatted JSON to test the behaivour of the methods when it happens.
    public static String jsonTestMalFormated = '{ ' +
                                                '"customerId": "identifier123",' + 
                                                '"serialNumber 27263927192",' + 
                                                '"mpxn": "14582749",' +
                                                '"read": ' +
                                                    '{"type": "ANYTIME", "registerId": "387373", "value": "2729"},' +
                                                    '{"type": "NIGHT", "registerId": "387373", "value": "2892"}' +
                                                '],' + 
                                                '"readDate": "2017-11-20T16:19:48+00:00Z"' + 
                                                '}';
    //JSON with a list of Meter Readers to check the behaivour if the process receive more than one
    public static String jsonTestMultiRecord =  '[{ ' +
                                                '"customerId": "identifier123",' + 
                                                '"serialNumber": "27263927192",' + 
                                                '"mpxn": "14582749",' +
                                                '"read": [' +
                                                    '{"type": "ANYTIME", "registerId": "387373", "value": "2729"},' +
                                                    '{"type": "NIGHT", "registerId": "387373", "value": "2892"}' +
                                                '],' + 
                                                '"readDate": "2017-11-20T16:19:48+00:00Z"' + 
                                                '},'+
                                                '{ ' +
                                                '"customerId": "identifier123",' + 
                                                '"serialNumber": "27263927192",' + 
                                                '"mpxn": "14582749",' +
                                                '"read": [' +
                                                    '{"type": "ANYTIME", "registerId": "387373", "value": "2729"},' +
                                                    '{"type": "NIGHT", "registerId": "387373", "value": "2892"}' +
                                                '],' + 
                                                '"readDate": "2017-11-20T16:19:48+00:00Z"' + 
                                                '}]';

    
}