CODING_CHALLENGE/MeterReader/force-app/main/default/objects/Meter_Reader__c/Meter_Reader__c.object-meta.xml
<CustomObject>
    <description>Holds the meter reader resume to be presented in the web component</description>
    <label>Meter Reader</label>
    <nameField>
        <displayFormat>MR-{000000}</displayFormat>
        <label>Meter Reader Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Meter Readers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

CODING_CHALLENGE/MeterReader/force-app/main/default/objects/Meter_Reader__c/fields/CustomerNameLgt__c.field-meta.xml
<CustomField>
    <fullName>CustomerNameLgt__c</fullName>
    <description>Field used to show the customer salesforce id in the table</description>
    <formula>Customer__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>CustomerNameLgt</label>
    <type>Text</type>
</CustomField>

CODING_CHALLENGE/MeterReader/force-app/main/default/objects/Meter_Reader__c/fields/MeterNameLgt__c.field-meta.xml
<CustomField>
    <fullName>MeterNameLgt__c</fullName>
    <description>Used to show the Meter Salesforce ID in the Meter Reader Table</description>
    <formula>Meter__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>MeterNameLgt</label>
    <type>Text</type>
</CustomField>

CODING_CHALLENGE/MeterReader/force-app/main/default/objects/Meter_Reader__c/fields/Submited_DateTime__c.field-meta.xml
<CustomField>
    <fullName>Submited_DateTime__c</fullName>
    <description>Holds the exact moment when the meter reader was submited</description>
    <label>Submited DateTime</label>
    <type>DateTime</type>
</CustomField>

CODING_CHALLENGE/MeterReader/force-app/main/default/objects/Meter_Reader__c/fields/SupplierNameLgt__c.field-meta.xml
<CustomField>
    <fullName>SupplierNameLgt__c</fullName>
    <description>Used to show the supplier salesforce ID in the Meter Reader table</description>
    <formula>Supplier__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>SupplierNameLgt</label>
    <type>Text</type>
</CustomField>

CODING_CHALLENGE/MeterReader/force-app/main/default/objects/Meter_Reader__c/fields/Total_Consumed__c.field-meta.xml
<CustomField>
    <fullName>Total_Consumed__c</fullName>
    <description>Holds the total consumed for the client and suplied for the reads in the meter reader</description>
    <label>Total Consumed</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

CODING_CHALLENGE/MeterReader/force-app/main/default/classes/MeterReaderController.cls
public with sharing class MeterReaderController 
{
    //Method to send the meter readers to the lightning web component.
    @AuraEnabled(cacheable=true)
    public static Meter_Reader__c[] getRecords()
    {
        //Return meter readers in the system sorted by create date.       
        return [SELECT Id, Name, CustomerNameLgt__c,MeterNameLgt__c, SupplierNameLgt__c, Total_Consumed__c, Submited_DateTime__c   
                FROM Meter_Reader__c 
                ORDER BY Submited_DateTime__c DESC
                LIMIT 10000];
    }
}